blank_issues_enabled: false
contact_links:
  - name: Slam Mirrorbot Channel
    url: https://t.me/SlamMirrorUpdates
    about: Update Channel
  - name: Slam Mirrorbot Group
    url: https://t.me/SlamSupport
    about: Support Group
  - name: Bug Report Group
    url: https://t.me/SlamBugReport
    about: Bug Report & Feature Request Group
